version: '0'

services:
  # Start the Database
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Shop
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_User: Python
      MYSQL_PASSWORD: Python
      MYSQL_HOST: '%'
      MYSQL_ROOT_HOST: '%'
      # MYSQL_ROOT_HOST: 0.0.0.0/255.255.255.248
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"

  #start the TableCreater
  Tablecreater:
    links:
      - "db:database"
    image: tablescreater:0.1

    
  
    
  # Start the API
  # TODO: Ports zuweisen
  API:
    image: apiservice:0.1
    links: 
      - "db:database"
      - "SecurityService:Securityapi"
    ports: 
      - "5000:5000"

  # Start the Authentication Service
  SecurityService:
    image: securityservice:0.1




volumes:
  db_data: {}


