version: '0'

services:
  # Start the Database
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Shop
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_User: Python
      MYSQL_PASSWORD: Python
      MYSQL_HOST: '%'
      MYSQL_ROOT_HOST: '%'
      # MYSQL_ROOT_HOST: 0.0.0.0/255.255.255.248
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"

  #start the TableCreater
  Tablecreater:
    links:
      - "db:database"
    image: tablescreater:0.1

  # -------------------------------------------
  # Start the API
  # TODO: Ports zuweisen
  API:
    image: apiservice:0.1
    links: 
      - "db:database"
      - "SecurityService:Securityapi"
    ports: 
      - "5000:5000"
    restart: always

  # Start the Authentication Service
  SecurityService:
    image: securityservice:0.1
    restart: always
    links: 
      - "db:database"

  # -------------------------------------------
  # Helper
  # Start the Helpers
  helpercustomer:
    image: helpercustomer:0.1
    links: 
      - "API:API"
    restart: always

  helperDeliverer:
    image: helperdeliverer:0.1
    links: 
      - "API:API"
    restart: always
  

  helperEmployer:
    image: helperemployer:0.1
    links: 
      - "API:API"
    restart: always

  # -------------------------------------------
  # Webpage
  StandartWebpage:
    image: standartwebpage:0.1
    links: 
      - "API:API"
    ports: 
      - "8080:8080"
    command: npm start
    restart: always

  AdminWebpage:
    image: adminwebpage:0.1
    links: 
      - "API:API"
    ports: 
      - "8081:8080"
    command: npm start
    restart: always


volumes:
  db_data: {}


